import type { Category, Product } from './types'
import set1Image from '../../../assets/sushi/Сет1.png'
import set2Image from '../../../assets/sushi/Сет2.png'
import set3Image from '../../../assets/sushi/Сет3.png'
import set4Image from '../../../assets/sushi/Сет4.png'
import set5Image from '../../../assets/sushi/Сет5 увел.png'

export const CATEGORIES: Category[] = [
  { id: 'sets', name: 'Наборы' },
  { id: 'rolls', name: 'Роллы и суши' },
  { id: 'onigiri', name: 'Ёнигири' },
  { id: 'tempura', name: 'Темпура' },
  { id: 'baked', name: 'Запечённые' },
  { id: 'premium', name: 'Премиум' },
  { id: 'hot', name: 'Горячее и салаты' },
  { id: 'drinks', name: 'Напитки и десерты' },
  { id: 'sauces', name: 'Соусы' },
  { id: 'spices', name: 'Специи' },
]

export const PRODUCTS: Product[] = [
  {
    id: 'set-himitsu',
    categoryId: 'sets',
    name: 'Химицу',
    image: set1Image,
    weight: '1 220 г',
    price: 1349,
    description: 'Сет роллов с мидиями, крабом, лососем и том ям.',
    details:
      'Мидия сальса запечённая, Краб темпура, Лосось чили-майо темпура, Том ям с креветкой, Лосось чили-майо с кунжутом.',
    badge: 'Лучшая цена без скидок',
  },
  {
    id: 'set-ma-sik',
    categoryId: 'sets',
    name: 'Ма Сик',
    image: set2Image,
    weight: '1 480 г',
    price: 1699,
    description:
      'Большой сет из 6 видов роллов с морепродуктами, рыбой и курицей.',
    details:
      'Калифорния с огурцом, Лава темпура, Спейшл NEW, Запечённая филадельфия с лососем и крабом, Цезарь BIG, Цезарь.',
  },
  {
    id: 'set-hikoki',
    categoryId: 'sets',
    name: 'Хикоки',
    image: set3Image,
    weight: '2 870 г',
    price: 2999,
    description:
      'Огромный сет с крабом, курицей, беконом и лососем для компании.',
    details:
      'Краб сладкий чили, Лава краб спайси, Запечённый с курицей, Тортилья с беконом, Калифорния с огурцом и другие.',
  },
  {
    id: 'set-premium-for-two',
    categoryId: 'sets',
    name: 'Премиум для двоих',
    image: set4Image,
    weight: '575 г',
    price: 2399,
    description: 'Стартовый набор успешного свидания.',
    details: 'Филадельфия "Роял", Нью-Йорк, Сяке, Эби.',
  },
  {
    id: 'set-premium',
    categoryId: 'sets',
    name: 'Премиум',
    image: set5Image,
    weight: '1 045 г',
    price: 2899,
    description: 'Набор роллов с лососем, морепродуктами и икрой.',
    details: 'Филадельфия "Роял", Флорида, Манхэттен, Калифорния эби.',
  },
  {
    id: 'roll-philadelphia-cucumber',
    categoryId: 'rolls',
    name: 'Филадельфия с огурцом',
    weight: '295 г',
    price: 799,
    description: 'Больше лосося - меньше стресса.',
    details: 'Лосось, сыр сливочный, огурец, рис, нори.',
  },
  {
    id: 'roll-california',
    categoryId: 'rolls',
    name: 'Калифорния',
    weight: '215 г',
    price: 369,
    description: 'Классический ролл с крабом и авокадо в тобико.',
    details: 'Рис, нори, майонез, авокадо, снежный краб, тобико.',
  },
  {
    id: 'roll-dragon',
    categoryId: 'rolls',
    name: 'Дракон',
    weight: '215 г',
    price: 669,
    description: 'Ролл с угрём, крабом и авокадо.',
    details: 'Крабовое мясо, угорь, авокадо, тобико, соус унаги.',
  },
  {
    id: 'roll-lava-syake',
    categoryId: 'rolls',
    name: 'Лава сяке',
    weight: '235 г',
    price: 409,
    description: 'Лосось под соусом лава с креветкой.',
    details: 'Лосось, огурец, сыр сливочный, соус лава.',
  },
  {
    id: 'roll-caesar',
    categoryId: 'rolls',
    name: 'Цезарь',
    weight: '210 г',
    price: 249,
    description: 'Ролл по мотивам салата "Цезарь" с курицей.',
  },
  {
    id: 'onigiri-salmon-teriyaki',
    categoryId: 'onigiri',
    name: 'Ёнигири лосось терияки',
    weight: '140 г',
    price: 509,
    description: 'Лосось терияки, сыр и рис.',
  },
  {
    id: 'onigiri-crab',
    categoryId: 'onigiri',
    name: 'Ёнигири с крабом',
    weight: '140 г',
    price: 179,
    description: 'Нежный краб и икра масаго в рисовом треугольнике.',
  },
  {
    id: 'tempura-philadelphia',
    categoryId: 'tempura',
    name: 'Филадельфия темпура',
    weight: '205 г',
    price: 349,
    description: 'Горячий ролл Филадельфия в хрустящей панировке.',
  },
  {
    id: 'tempura-ebi',
    categoryId: 'tempura',
    name: 'Эби темпура',
    weight: '185 г',
    price: 299,
    description: 'Креветка темпура с сыром и пикантным соусом.',
  },
  {
    id: 'baked-salmon-spicy',
    categoryId: 'baked',
    name: 'Запечённый с лососем спайси',
    weight: '235 г',
    price: 369,
    description: 'Запечённый ролл с лососем и соусом спайс.',
  },
  {
    id: 'baked-crab',
    categoryId: 'baked',
    name: 'Запечённый с крабом',
    weight: '245 г',
    price: 279,
    description: 'Запечённый ролл с крабом и сыром гауда.',
  },
  {
    id: 'premium-florida',
    categoryId: 'premium',
    name: 'Флорида',
    weight: '265 г',
    price: 699,
    description: 'Креветка, огурец и икра тобико.',
  },
  {
    id: 'premium-philadelphia-royal',
    categoryId: 'premium',
    name: 'Филадельфия "Роял"',
    weight: '310 г',
    price: 899,
    description: 'Лосось, икра и краб для ужина по-королевски.',
  },
  {
    id: 'hot-poke-salmon',
    categoryId: 'hot',
    name: 'Поке с лососем + 1 соус',
    weight: '260 г',
    price: 585,
    description: 'Поке с лососем, овощами и рисом.',
  },
  {
    id: 'hot-tom-yam',
    categoryId: 'hot',
    name: 'Том Ям',
    weight: '335 г',
    price: 689,
    description: 'Классический суп том ям с креветкой и кокосовым молоком.',
  },
  {
    id: 'drink-yobidoyobi-cola',
    categoryId: 'drinks',
    name: 'Сливочная кола Ёбидоёби',
    weight: '330 мл',
    price: 129,
  },
  {
    id: 'dessert-mochi-mango',
    categoryId: 'drinks',
    name: 'Моти манго-маракуйя',
    weight: '40 г',
    price: 275,
  },
  {
    id: 'dessert-cheesecake-ny',
    categoryId: 'drinks',
    name: 'Чизкейк New York',
    weight: '100 г',
    price: 329,
  },
  {
    id: 'sauce-lava',
    categoryId: 'sauces',
    name: 'Соус Лава',
    weight: '30 г',
    price: 89,
  },
  {
    id: 'sauce-spice',
    categoryId: 'sauces',
    name: 'Соус Спайс',
    weight: '30 г',
    price: 79,
  },
  {
    id: 'sauce-unagi',
    categoryId: 'sauces',
    name: 'Соус Унаги',
    weight: '30 г',
    price: 79,
  },
  {
    id: 'spice-ginger',
    categoryId: 'spices',
    name: 'Имбирь',
    weight: '25 г',
    price: 39,
  },
  {
    id: 'spice-wasabi',
    categoryId: 'spices',
    name: 'Васаби',
    weight: '10 г',
    price: 30,
  },
  {
    id: 'spice-set',
    categoryId: 'spices',
    name: 'Васаби, имбирь, соевый соус',
    weight: '75 г',
    price: 99,
  },
]
